version: "3.9"
services:
  web.quiz-lti.local.inseng.net:
    build: .
    ports:
      - "9000:80"
    labels:
      - "traefik.enable=true"
  redis.quiz-lti:
    image: "redis:alpine"
networks:
  default:
    external: true
    name: test-net