version: "3.9"
services:
  quiz_lti.web:
    build: .
    ports:
      - "9000:80"
    labels:
      - "traefik.enable=true"
  quiz_lti.redis:
    image: "redis:alpine"
networks:
  default:
    external: true
    name: test-net