version: "3.9"

x-aliases:
  - &serviceHost web.quiz-lti.local.inseng.net

services:
  quiz_lti.web:
    build: .
    ports:
      - "9000:80"
    labels:
      instructure.serviceHost: *serviceHost
      traefik.enable: true
    networks:
      default:
        aliases:
          - *serviceHost
  quiz_lti.redis:
    image: "redis:alpine"
networks:
  default:
    external: true
    name: test-net