version: "3.9"
services:
  web.quiz-api.local.inseng.net:
    build: .
    ports:
      - "8000:80"
    labels:
      - "traefik.enable=true"
  quiz_api.redis:
    image: "redis:alpine"
networks:
  default:
    external: true
    name: test-net