version: "3.9"

x-aliases:
  - &serviceHost web.quiz-api.local.inseng.net

services:
  quiz_api.web:
    build: .
    ports:
      - "8000:80"
    labels:
      instructure.serviceHost: *serviceHost
      traefik.enable: true
    networks:
      default:
        aliases:
          - *serviceHost
  quiz_api.redis:
    image: "redis:alpine"
networks:
  default: 
    external: true
    name: test-net